sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t ruszczus/react-test -f ./client/Dokcerfile.dev ./client

script:
  - docker run -e CI=true ruszczus/react-test npm test

