language: general
node_js:
  - "stable"
sudo: required

services:
  - docker

before_install:
  - docker build -t ruszczus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ruszczus/react-test  npm test

after_success:
  - docker build -t ruszczus/multi-client ./client
  - docker build -t ruszczus/multi-nginx ./nginx
  - docker build -t ruszczus/multi-server ./server
  - docker build -t ruszczus/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ruszczus/multi-client
  - docker push ruszczus/multi-nginx
  - docker push ruszczus/multi-server
  - docker push ruszczus/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-848957435488
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
