language: generic 
node_js:
  - 8
sudo: required

services:
  - docker

before_install:
  - docker build -t ruszczus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ruszczus/react-test npm test

after_success:
  - docker build -t ruszczus/multi-client ./client
  - docker build -t ruszczus/multi-nginx ./nginx
  - docker build -t ruszczus/multi-server ./server
  - docker build -t ruszczus/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ruszczus/multi-client
  - docker push ruszczus/multi-nginx
  - docker push ruszczus/multi-server
  - docker push ruszczus/multi-worker